### PR TITLE
add link to 'parallel' vignette

### PR DESCRIPTION
**Pull request by timflutre**
As it is not on CRAN, it's a bit harder to find.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Really good idea in principle.  But given that every R installation has it, should we maybe just suggest

```r
vignette("parallel", package="parallel")
```

or even 

```r
vignette("parallel")
```

Thoughts?   (Also, pointing to the r-devel version can be sketchy, R-release is probably better).

**Comment by timflutre** [comment]
Indeed, `vignette("parallel")` would be better. I'll make another pull request.

**Comment by eddelbuettel** [comment]
You can just reopen this one and pile a 2nd commit on top of the first.

**Comment by timflutre** [comment]
Sorry, it will be easier for me to make another pull request.

**Comment by eddelbuettel** [comment]
Not really.  You just edit, save and commit again.  Really does not get any easier.  Anyway ...

**Pull request closed without merging**
