### PR TITLE
add reference to rslurm package

### PR DESCRIPTION
**Pull request by grahamjeffries**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Good idea, but that is now it works -- you must edit the .ctv file.  

The .md file is generated.  The flow is from .svn to .md.  Note how CRAN packages are listed between the XML-alike brackets in the text,  and again at the bottom in the (alphabetical) list.

**Review by eddelbuettel — CHANGES_REQUESTED** [review]
Edit the ctv file instead.

**Comment by grahamjeffries** [comment]
Ah I see. Rebased and committed changes to the .ctv. How's that look?

**Comment by eddelbuettel** [comment]
That's better. Thanks. I'll finish it by creating an updated md and, importantly, push to SVN too.

**Review by eddelbuettel — APPROVED** [review]

**Pull request merged**
