### PR TITLE
Fixed deprecation warning using github-flavoured markdown

### PR DESCRIPTION
**Pull request by terrytangyuan**
[WARNING] Deprecated: markdown_github. Use gfm instead.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
What pandoc version do you have?  I don't think I have seen this:

```sh
edd@rob:~/git/ctv-finance(master)$ ./ctv2md.r 
Done.
edd@rob:~/git/ctv-finance(master)$ 
```

Or maybe the shell swallows it...

```sh
edd@rob:~/git/ctv-finance(master)$ pandoc --version
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.1, skylighting 0.3.3.1
Default user data directory: /home/edd/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
edd@rob:~/git/ctv-finance(master)$ 
```

**Comment by terrytangyuan** [comment]
Yea seems like shell swallows it. It only happens with RStudio.

**Comment by eddelbuettel** [comment]
And with your change:

```
edd@rob:~/git/ctv-finance(master)$ ./ctv2md.r 
pandoc: Unknown writer: gfm
Done.
edd@rob:~/git/ctv-finance(master)$ 
```

So the suggested change is (currently) of no value to me.

**Comment by terrytangyuan** [comment]
It's deprecated (search for "markdown_github has been deprecated in favor of gfm" [here](https://pandoc.org/releases.html)). 

I have the same version as yours but maybe you have multiple versions installed and R is using the different version (or me):
```
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
Default user data directory: /Users/terrytangyuan/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

That being said, feel free to close this since it's just deprecation warning and `markdown_github` would work for both of us.

**Comment by eddelbuettel** [comment]
RStudio ships its own (which IIRC is 2.*) and I would not be surprised if it defaulted to it.

I'll leave this open as a reminder for the day things will break for me when Ubuntu gets me 2.*.

**Comment by terrytangyuan** [comment]
I am cleaning up my pending PRs and I am going to close this one for now. I think you'll get a sensible error message once you upgraded to`2.*`, e.g. `pandoc: Unknown writer: markdown_github`.

**Comment by eddelbuettel** [comment]
Absolutely, there will be errors -- I was unaware of this before you brought it up.  But I agree that long-pending PRs are suboptimal.  We'll revisit.

**Pull request closed without merging**
