### PR TITLE
Add dqrng and rstream to parallel RNG section

### PR DESCRIPTION
**Pull request by rstub**
As discussed on SO here the PR to add dqrng (and rstream) to the parallel RNG section.

The second commit, which fixes the MD creation in the case of multiple links, is only in so fat related, as I wondered why my changes to the README looked so strange. I can separate that out if you prefer.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thanks -- but I used the same converter script for multiple years. Please explain why it needs fixing.

It is easier to just assess changes to the .ctv. Other stuff appears to have changed in  the .md than I am less sure about.

**Comment by rstub** [comment]
Sure. See the paragraph that I changed in the current MD file (with line breaks for better readability):
```
-   Random-number generators for parallel computing are available via the 
[rlecuyer](https://cran.r-project.org/package=rlecuyer/index.html) package, 
as well as the [sitmo](../packages/sitmo) package.
```

The first link looks odd with the `/index.html` at the end, while the second link is broken. Things got worse with my first commit:

```
-   Random-number generators for parallel computing are available via the 
[rlecuyer](https://cran.r-project.org/package=rlecuyer/index.html) package,
 the [rstream](../packages/rstream/index.html) package,
 the [sitmo](../packages/sitmo/index.html) package as well as
 the [dqrng](../packages/dqrng) package.
```

The first link is as it is now. All other links are broken, but it is interesting that for the last link the `/index.html` was removed.

This does not only affect this particular paragraph but all paragraphs with more than one link in it. In all these cases only the first link works. See for example the paragraph on Rmpi:

```
-   In recent years, the alternative MPI (Message Passing Interface) standard has become
 the de facto standard in parallel computing. It is supported in R via the 
[Rmpi](https://cran.r-project.org/package=Rmpi/index.html) by Yu. 
[Rmpi](../packages/Rmpi/index.html) package is mature yet actively maintained and offers 
access to numerous functions from the MPI API, as well as a number of R-specific extensions. 
[Rmpi](../packages/Rmpi) can be used [...]
```

The reason for this is the regular expression used to correct the links:
```
###  - make the implicit URL to packages explicit
       "-e's|../packages/\\(.*\\)/index.html|https://cran.r-project.org/package=\\1|g' ",
                         ^^^^^^^^
```

If there are more than one link in a paragraph, which is output as single line, the highlighted part of the regex will grab everything between the start of the first link and the end of the last link. This explains why the first link was transformed but with `/index.html` while the other links where not. Only the last link got the `/index.html` removed. There are ways to change the "greediness" of regexes, but I am not sure if they work with `sed`. The fix I am proposing is to use

```
###  - make the implicit URL to packages explicit
       "-e's|../packages/\\([^/]*\\)/index.html|https://cran.r-project.org/package=\\1|g' ",
                         ^^^^^^^^^^^
```

Instead of allowing everything between the known start and end of a link, this forbids slashes and thereby limits the regex to one link at a time. Unfortunately this changes several places in the MD file, and the diff is rather messy since all these places are (very) long lines. That is inevitable in this case, but as I said, I can split this up if you prefer so.

**Comment by eddelbuettel** [comment]
Ouch.  That was a lot on morning coffee.  Let's open a new issue on the converter script then.

**Comment by eddelbuettel** [comment]
And once we do, I can get Achim in here who by now is at least mildly interesting in markdown interfaces to/from ctv so maybe we just fix this "right" in R code in his ctv package.

**Comment by rstub** [comment]
Ok, I have removed the second commit and opened #22 instead.

**Pull request merged**
