### PR TITLE
Update the description of drake

### PR DESCRIPTION
**Pull request by wlandau-lilly**
Effective in the CRAN release of [version 4.4.0](https://github.com/wlandau-lilly/drake/releases/tag/v4.4.0), the high-performance computing backends in [drake](https://github.com/wlandau-lilly/drake) include `future_lapply()`, which connects to `batchtools` via `future.batchtools`. Now, it is straightforward to configure [drake](https://github.com/wlandau-lilly/drake) for formal resource managers such as SLURM, TORQUE, and the Univa Grid Engine.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Sorry, Will.  That doubles your wordcount.  This is a generic HPC TaskView, not a drake advertisement.  If you can keep the size in line with what other packages have submit anew.

**Comment by wlandau-lilly** [comment]
Good point. I will adjust.

**Comment by wlandau-lilly** [comment]
Thanks!

**Comment by eddelbuettel** [comment]
The final version was really good. Lemme run over and see if Achim's side changed something recently.

**Pull request merged**
