### PR TITLE
Include {targets} and update {drake}

### LINKED ISSUE #30: Suggestion: update drake description and mention targets
[`targets`](https://cran.r-project.org/package=targets), the long-term successor of [`drake`](https://cran.r-project.org/package=drake), just arrived on CRAN. In addition, the description of [`drake`](https://cran.r-project.org/package=drake)'s parallel backends is out of date. May I submit a PR to update this part of the task view?

### PR DESCRIPTION
**Pull request by wlandau**
This PR mentions [`targets`](https://github.com/ropensci/targets), the successor to [`drake`](https://github.com/ropensci/drake). It also updates the parallel backends of the latter. Fixes #30.

### CODE REVIEW

**Comment by wlandau** [comment]
I am sorry, the `README.md` file seems to have rendered differently on my machine, and there are a lot of trivial formatting changes. Should I open a new PR that only changes the XML file?

**Comment by eddelbuettel** [comment]
That ... is weird.  There is next-to-nothing to the converter.  Maybe I have an older / different version of package `ctv` (as that one is not on CRAN (if I remember correctly...) and hence not updated in my usual waves of `update.packages()`.  I have 

```
edd@rob:~/git/ctv-hpc(master)$ Rscript -e 'sapply(c("ctv", "XML"), function(x) format(packageVersion(x)))'
       ctv        XML 
   "0.8.5" "3.99.0.5" 
edd@rob:~/git/ctv-hpc(master)$
```

and I see ctv is now at 0.9.0.   Might be best to decouple this and remove the md file from the PR and I deal with that locally (and will see about updating then).

**Comment by eddelbuettel** [comment]
New plan!

I upgraded and will just push a new version.  Can you simply rebase?   

_Update_  That made fewer changes.  So that is not it.  I recommend you still rebase (for a cleaner commit history) but also remove the md file.  Else I could just squash if you were to just remove the md file.

**Comment by eddelbuettel** [comment]
Thanks.  It's still a bit weird because now I would merge deletion of README.md which is less that ideal.

Do you think we can redo the PR without README.md?

**Comment by wlandau** [comment]
> Thanks. It's still a bit weird because now I would merge deletion of README.md which is less that ideal.

I was hoping that would not happen.

> Do you think we can redo the PR without README.md?

Absolutely.

**Comment by eddelbuettel** [comment]
Really appreciate it.  Mud-wrestling `git` is an under-appreciated component of open source work ;-)

**Comment by wlandau** [comment]
I think we decided this was superseded by #32.

**Pull request closed without merging**
